# Generated by Django 3.2.6 on 2021-09-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_auto_20210830_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_bestselling',
            new_name='is_bestseller',
        ),
    ]
