# Generated by Django 3.2.6 on 2021-09-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0004_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='', max_length=80, unique=True),
        ),
    ]
