# Generated by Django 3.2.7 on 2021-09-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0010_auto_20210905_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='cover.jpg', upload_to='covers'),
            preserve_default=False,
        ),
    ]
