# Generated by Django 3.2.6 on 2021-09-05 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['-date'], 'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=15)),
                ('welcome_mesage', models.CharField(max_length=150)),
                ('about', models.TextField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='blogs', to='blog.author')),
            ],
        ),
    ]
