# Generated by Django 3.2.6 on 2021-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210905_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='authors/profile.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
