# Generated by Django 3.2.6 on 2021-09-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
