# Generated by Django 3.2.6 on 2021-09-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_comment_postcomment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'get_latest_by': ['-date'], 'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='blog.Tag'),
        ),
    ]
